### PR TITLE
Support for new FIDO javascript API and using multiple tokens

### PR DESCRIPTION
**Pull request by YuvalJoseph**
Hi.
I implemented the messages according to the latest FIDO javascript API.
This requires using HTTPS so Chrome native U2F won't send BAD REQUEST due to wrong appId.
So no need in Chrome extension anymore and there is also support for multiple tokens, so the demo server will allow registering more than one key
Kind Regards,
Yuval Joseph

### CODE REVIEW

**Comment by tstranex** [comment]
Hi Yuval

Thanks for sending the pull request. I agree it's better to use switch to the native JS API rather than the old Chrome extension.

There are a couple of changes needed before I can merge this:
- SignRequest and RegisterRequest changes: Multiple keys can always be handled by the client themselves - I don't think it worth breaking backward API compatibility for this. So I think the changes to auth.go and messages.go should be reverted.
- Indentation and comments in u2fdemo/main.go. Also keep registration as []byte rather than u2f.Registration since this is demonstrating how it would be stored in a database.

If you feel motived to make the changes and willing to iterate a couple of times, then you're welcome to go ahead. :) Otherwise, I'll manually merge in the JS API change as a new commit tomorrow.

Regards,
Timothy

**Comment by YuvalJoseph** [comment]
Hi Timothy

Thanks for reviewing my pull request. Of course I am willing to change my code. I will of course remove the comments and will run go format on main.go
- For supporting the new javascript API the changes I did in messages.go and auth.go are mandatories
  the sign request using your code looked like
  {version: "U2F_V2", challenge: "7kozMX4EGFKYqmFOjLPD7QCHyJc7n3Pt0DHigNGf2aU",…}
  appId: "http://localhost:8080"
  challenge: "7kozMX4EGFKYqmFOjLPD7QCHyJc7n3Pt0DHigNGf2aU"
  keyHandle: "nLfGtT8E7EKT5zo9t4zvVPK7qjJQoXqTDD_WHKh64X99LYARhRZc5hb-49AlQYNQcJhkk3ujHeaY5ti9rshrKQ"
  version: "U2F_V2"

when the new API requires the sign requests to be an array
{
  "type": "u2f_sign_request",
  "signRequests": [
    { "version": "U2F_V2", "challenge": ..., "appId": ..., keyHandle, <key handle 1>},
    { "version": "U2F_V2", "challenge": ..., "appId": ..., keyHandle, <key handle 2>},
    ...
  ]
}

In addition I am not sure what do you mean "Multiple keys can always be handled by the client themselves" If I'm using to token for my account (let's say yubikey and google authenticator) the server is expected to send all the key handle to the FIDO client (Chrome browser or extension) and the FIDO client handle it. 

Cheers,

Yuval

**Comment by tstranex** [comment]
Hi Yuval

Sorry for the delayed response. Regarding the messages.go and auth.go changes: Yeah, I agree the server has to send all the key handles to the client. What I meant is that this part should be handled by the server outside the u2f package because not every user of the u2f package will want to do it this way (AuthenticateRequest isn't part of the U2F specification).

What I'd recommend is move the code for handling multiple sign requests into u2fdemo/main.go instead. You could just change signRequest() in main.go to return a []u2f.SignRequest response and create it by calling u2f.SignRequest multiple times.

Does that make sense?

Regards,
Timothy

**Comment by YuvalJoseph** [comment]
Hi,

I see your point, I think the API is going to be a little bit more complicated that way and the package users will need to implement more code but since we are writing the usage example it should be fine.
I will make these changes and push an update in the nearest days

Yuval

**Comment by YuvalJoseph** [comment]
Done

**Comment by tstranex** [comment]
Thanks!

**Pull request merged**
